force-app/main/default/objects/Evaluation__c/Evaluation__c.object-meta.xml
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <displayFormat>Eval-{0000}</displayFormat>
        <label>Evaluation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Evaluation__c/fields/Further_Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Further_Evaluation__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Further Evaluation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Evaluation__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <formula>( Passing__c + Defensive_Awareness__c + Shooting_Ability__c +  Technique__c +   Tracking_Back__c + Match_Intelligence__c) /6</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EvalTriggerHandler.cls
public with sharing class EvalTriggerHandler {
    
    public Static void updatePlayercard(List<Evaluation__c> triggernew) {

   List<Evaluation__c > playerName = new List<Evaluation__c >();

        for (Evaluation__c pId : triggernew){

            playerName.add(pId);

        }
    List<Evaluation__c> furtherEval = new List<Evaluation__c>();

        For(List <Evaluation__c> playerRating:[Select Name,  Total__c, Further_Evaluation__c from Evaluation__c ]){
         	
            for (Evaluation__c pRating : playerRating){
                
                if (pRating.Total__c >= 7.5){
                    
                    pRating.Further_Evaluation__c = true; 
                }
                
            }
            
        
           

        }
insert furtherEval;

    }

    }