force-app/main/default/objects/Player_Application__c/Player_Application__c.object-meta.xml
<CustomObject>
    <label>Player Card</label>
    <nameField>
        <displayFormat>Card= {0000}</displayFormat>
        <label>Player Card Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Cards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Player_Application__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Agent?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player_Application__c/fields/Under_18__c.field-meta.xml
<CustomField>
    <fullName>Under_18__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Under 18</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PlayerCardTriggerHandler.cls
public with sharing class PlayerCardTriggerHandler {
    public void  validateRep(List<Player_Application__c> validateRep) {
    
        for(Player_Application__c checkPlayerRep: validateRep){
                    if (!checkPlayerRep.Agent__c && !checkPlayerRep.Under_18__c){
                        checkPlayerRep.addError('Stop!!');

                    }
                
                }
            }
        }
    